   178.2ms (setup:858): 2025-04-28 15:08:57
   178.3ms (setup:859): /usr/bin/pipx install google-api-python-client google-auth-httplib2 google-auth-oauthlib
   178.3ms (setup:860): pipx version is 1.4.3
   178.3ms (setup:861): Default python interpreter is '/usr/bin/python3'
   179.0ms (package_name_from_spec:370): Determined package name: google-api-python-client
   179.0ms (package_name_from_spec:371): Package name determined in 0.0s
   179.6ms (package_name_from_spec:370): Determined package name: google-auth-httplib2
   179.6ms (package_name_from_spec:371): Package name determined in 0.0s
   179.7ms (package_name_from_spec:370): Determined package name: google-auth-oauthlib
   179.7ms (package_name_from_spec:371): Package name determined in 0.0s
   180.2ms (run_subprocess:168): running /usr/bin/python3 -m venv --without-pip /home/ssm-user/.local/share/pipx/venvs/google-api-python-client
   235.1ms (run_subprocess:190): stdout:
   235.2ms (run_subprocess:192): stderr:
   235.2ms (run_subprocess:193): returncode: 0
   235.6ms (run_subprocess:168): running <checking pip's availability>
   254.6ms (run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7c79893ffcb0>, origin='/home/ssm-user/.local/share/pipx/shared/lib/python3.12/site-packages/pip/__init__.py', submodule_search_locations=['/home/ssm-user/.local/share/pipx/shared/lib/python3.12/site-packages/pip'])
   254.7ms (run_subprocess:193): returncode: 0
   254.8ms (run_subprocess:168): running /home/ssm-user/.local/share/pipx/venvs/google-api-python-client/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   274.4ms (run_subprocess:190): stdout: /home/ssm-user/.local/share/pipx/venvs/google-api-python-client/lib/python3.12/site-packages
   274.4ms (run_subprocess:193): returncode: 0
   274.6ms (run_subprocess:168): running /home/ssm-user/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
   293.0ms (run_subprocess:190): stdout: /home/ssm-user/.local/share/pipx/shared/lib/python3.12/site-packages
   293.0ms (run_subprocess:193): returncode: 0
   293.2ms (run_subprocess:168): running /home/ssm-user/.local/share/pipx/venvs/google-api-python-client/bin/python --version
   294.8ms (run_subprocess:190): stdout: Python 3.12.3
   294.8ms (run_subprocess:192): stderr:
   294.8ms (run_subprocess:193): returncode: 0
   295.0ms (_parsed_package_to_package_or_url:137): cleaned package spec: google-api-python-client
   295.9ms (run_subprocess:168): running /home/ssm-user/.local/share/pipx/venvs/google-api-python-client/bin/python -m pip --no-input install google-api-python-client
  4417.6ms (run_subprocess:193): returncode: 0
  4419.2ms (run_subprocess:168): running <fetch_info_in_venv commands>
  4513.3ms (run_subprocess:190): stdout: {"sys_path": ["/usr/lib/python312.zip", "/usr/lib/python3.12", "/usr/lib/python3.12/lib-dynload", "/home/ssm-user/.local/share/pipx/venvs/google-api-python-client/lib/python3.12/site-packages", "/home/ssm-user/.local/share/pipx/shared/lib/python3.12/site-packages"], "python_version": "3.12.3", "environment": {"implementation_name": "cpython", "implementation_version": "3.12.3", "os_name": "posix", "platform_machine": "x86_64", "platform_release": "6.8.0-1027-aws", "platform_system": "Linux", "platform_version": "#29-Ubuntu SMP Thu Mar 27 17:28:55 UTC 2025", "python_full_version": "3.12.3", "platform_python_implementation": "CPython", "python_version": "3.12", "sys_platform": "linux"}}
  4513.3ms (run_subprocess:193): returncode: 0
  4639.1ms (get_venv_metadata_for_package:339): get_venv_metadata_for_package: 220ms
  4639.2ms (_parsed_package_to_package_or_url:137): cleaned package spec: google-api-python-client
  4639.8ms (rmdir:55): removing directory /home/ssm-user/.local/share/pipx/venvs/google-api-python-client
  4734.6ms (cli:924): PipxError: No apps associated with package google-api-python-client. Try again with '--include-deps' to include apps of dependent packages, which are
listed above. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 100, in install
    run_post_install_actions(
  File "/usr/lib/python3/dist-packages/pipx/commands/common.py", line 427, in run_post_install_actions
    raise PipxError(
pipx.util.PipxError: No apps associated with package google-api-python-client. Try again with '--include-deps' to include apps of dependent packages, which are
listed above. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
  4744.9ms (cli:932): pipx finished.
